# Author: Sos1ska
# Link GitHub -> https://github/Sos1ska
# Link VK -> https://vk.com/nikitasos1ska
vbOKOnly = "vbOKOnly"
vbOKCancel = "vbOKCancel"
vbAbortRetryIgnore = "vbAbortRetryIgnore"
vbYesNoCancel = "vbYesNoCancel"
vbYesNo = "vbYesNo"
vbRetryCancel = "vbRetryCance"
vbCritical = "vbCritical"
vbQuestion = "vbQuestion"
vbExclamation = "vbExclamation"
vbInformation = "vbInformation"
vbDefaultButton1 = "vbDefaultButton1"
vbDefaultButton2 = "vbDefaultButton2"
vbDefaultButton3 = "vbDefaultButton3"
vbDefaultButton4 = "vbDefaultButton4"
vbApplicationModal = "vbApplicationModal"
vbSystemModal = "vbSystemModal"
vbMsgBoxHelpButton = "vbMsgBoxHelpButton"
vbMsgBoxSetForeground = "vbMsgBoxSetForeground"
vbMsgBoxRight = "vbMsgBoxRight"
vbMsgBoxRtlReading = "vbMsgBoxRtlReading"